language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.1
gemfile:
  - gemfiles/Gemfile.rails-4.0-stable
  - gemfiles/Gemfile.rails-4.1-stable
  - gemfiles/Gemfile.rails-4.2-stable
  - Gemfile
cache: bundler    
before_install: "rm ${BUNDLE_GEMFILE}.lock" 
before_script: "bundle update" 
before_script:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'bundle exec rake db:migrate RAILS_ENV=test'
addons:
  code_climate:
    repo_token: 9c8761c2808bbbe075f50dc73ede02b8d9128ce0df821cb3f3df8d44f8993671