branches:
  only:
    - master
language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.1
env:
  - "RAILS_VERSION=4.0"
  - "RAILS_VERSION=4.1"
  - "RAILS_VERSION=4.2"
  - "RAILS_VERSION=default"
before_script:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'bundle exec rake db:migrate RAILS_ENV=test'
addons:
  code_climate:
    repo_token: 9c8761c2808bbbe075f50dc73ede02b8d9128ce0df821cb3f3df8d44f8993671