# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fce0c168c2e8cf4ba582289a0da50bd355fab3690725511095b18846994119488c8d682286d44a00e82d67da25117e8dddf8f7ed988f743ae0fc72324838093

test:
  secret_key_base: c1314518427ad301986ad49ab4a66dc99a86361f8e563fa96ef42f5a7ea4df0e68aa433079b86f07038ca37bc4ebf03a80f9b6da7b16206e3a920947ba2684aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
